### ISSUE TITLE
Hello, is it possible to use this theme with wintercms?

### ISSUE THREAD

**Issue by ad-sharky** [RatMD/newshub-theme#3]
Hello, is it possible to use this theme with wintercms?

**Comment by SamDeny** [comment]
Hello,

I don't know, I haven't tested it for WinterCMS. 

As far as I know, WinterCMS is a fork of OctoberCMS **v1** and this template is optimized and developed for v2 and v3, thus I guess it won't work, but of course I can't tell for sure.

**Comment by ad-sharky** [comment]
Hello, yes, indeed, after installation I encountered a number of problems, the template was installed on winter version 1.2.0

**Comment by SamDeny** [comment]
Hello again,

Well... NewsHub also relies on a few core plugins and my own BlogHub one. The most core extensions will have an equivalent WinterCMS version for sure, but BlogHub definitively needs to be adapted for WinterCMS. 

I'm currently working on v1.3.0, I'll then take look at a WinterCMS port for both, but I can't promise anything yet.

**Comment by ad-sharky** [comment]
Hello, it would not be bad, unfortunately my knowledge is not enough to adapt it myself.

**Comment by pbsmultimedia** [comment]
+1
